### ISSUE TITLE
BUG: API returning 502 http response on authentication request

### ISSUE THREAD

**Issue by ErickHMT** [iomateapp/api#13]
**Describe the bug**
When trying an auth request in the studio the API is returning HTTP status 502 with no JSON response

**To Reproduce**
1. Send a request to [the API](https://api.iomate.app/authentication) with the payload `{email: "valid@email.com", password: "validpassword"}`
3. See status code '502' with no valid response

**Expected behavior**
The API should return the list of login errors or an HTTP status 200 with a valid token for authentication

**Screenshots**
![image](https://user-images.githubusercontent.com/19320921/190920877-2d613700-e943-4b3b-a68c-7763a0e03986.png)
![image](https://user-images.githubusercontent.com/19320921/190920689-83bf67ae-4a88-46bc-a4ff-4bfbebf76ca7.png)

**Comment by roderiano** [comment]
> **Describe the bug** When trying an auth request in the studio the API is returning HTTP status 502 with no JSON response
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Send a request to [the API](https://api.iomate.app/authentication) with the payload `{email: "valid@email.com", password: "validpassword"}`
> 2. See status code '502' with no valid response
> 
> **Expected behavior** The API should return the list of login errors or an HTTP status 200 with a valid token for authentication
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/19320921/190920877-2d613700-e943-4b3b-a68c-7763a0e03986.png) ![image](https://user-images.githubusercontent.com/19320921/190920689-83bf67ae-4a88-46bc-a4ff-4bfbebf76ca7.png)


The bug is occurring because the database service import failed. 

Evidence:
![evidence](https://user-images.githubusercontent.com/17568800/190923354-3e6edd07-53ed-4373-886f-4bfdb78e0358.png)

**Comment by roderiano** [comment]
Fix applied.

![evidence](https://user-images.githubusercontent.com/17568800/190923761-1163b8e0-12f8-4725-87ce-953fd9475e51.png)
