### ISSUE TITLE
FEATURE: Add coutries endpoint

### ISSUE THREAD

**Issue by ErickHMT** [iomateapp/api#9]
**Describe the solution you'd like**
it is necessary to create an endpoint for the list of countries that will be used for validation during user registration.

**Comment by roderiano** [comment]
The attributes of the [Countries ](https://github.com/iomateapp/api/blob/main/models/countries.py)model will be used. It will be made available in a new endpoint using the get method.

**Comment by roderiano** [comment]
Add **[GET]** _/dev/countries_ route.

![evidence](https://user-images.githubusercontent.com/17568800/190924401-5edcbf64-f1f0-418d-9fb1-cd6413fdca18.png)

This route requires user authentication.
